### PR TITLE
fix: accessibility bugs with the VolumeBar

### LINKED ISSUE #4021: aria-valuenow and aria-valuetext are not initially set correctly
## Description
The initial state of the volume slider has `aria-valuenow` set to 0, and no `aria-valuetext` attribute. As a result, a screen reader (e.g. VoiceOver on macOS) announces the slider as "0, volume level), even though the volume is set to (and displayed as) 100%. The `aria-valuetext` is not set until the volume is changed.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. On a Mac, turn on VoiceOver (command-F5)
2. Open a page with the video.js player, in Safari
3. Use the Tab key to move keyboard focus to the Big Play Button, and press Enter
4. Use the Tab key to move focus into the Control Bar, and then onto the volume control slider

### Expected
Expect VoiceOver to announce (and display) that the volume is 100%

### Actual
VoiceOver announces "0, volume level"

### Error output
_None_

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
v6.0.0-RC.1
#### browsers
Safari with VoiceOver (and probably others)
#### OSes
macOS (Sierra, 10.12.2)
### plugins
_No_

### LINKED ISSUE #4022: The aria-valuetext for the volume control slider contains two decimal places on a 0 to 100% scale!
## Description
Screen reader announces volume as, e.g. "eight-point-zero-zero-percent". Since a keyboard-only user can only move the volume control in steps of 10, the two decimal places of precision in `aria-valuetext` are completely unnecessary!

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Use a screen reader, such as VoiceOver on macOS, to read out the value of the volume control slider!

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
v6.0.0-RC.1
#### browsers
All
#### OSes
All
### plugins
_none_

### PR DESCRIPTION
**Pull request by BrandonOCasey**
## Description
* Fixes #4021: `aria-valuenow` and `aria-valuetext` not set initially
* Fixes #4022: drop the decimal places on `aria-valuenow` and `aria-valuetext`

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [x] If necessary, more likely in a feature request than a bug fix
  - [x] Change has been verified in an actual browser (Chome, Firefox, IE)
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

File: src/js/control-bar/volume-control/volume-bar.js [hunk 1]
```diff
@@ -27,7 +27,7 @@ class VolumeBar extends Slider {
     super(player, options);
     this.on('slideractive', this.updateLastVolume_);
     this.on(player, 'volumechange', this.updateARIAAttributes);
-    player.ready(() => this.updateARIAAttributes);
+    player.ready(() => this.updateARIAAttributes());
```
Comment (gkatsev) [inline src/js/control-bar/volume-control/volume-bar.js]: heh

File: src/js/control-bar/volume-control/volume-bar.js [hunk 2]
```diff
@@ -106,7 +106,7 @@ class VolumeBar extends Slider {
    */
   updateARIAAttributes(event) {
     // Current value of volume bar as a percentage
-    const volume = (this.player_.volume() * 100).toFixed(2);
+    const volume = Math.round((this.player_.volume() * 100).toFixed(2));
```
Comment (gkatsev) [inline src/js/control-bar/volume-control/volume-bar.js]: no need to the `.toFixed()`, that's what adds the two decimal places. Maybe just a `.toString()`

**Comment by BrandonOCasey** [comment]
I wasn't even aware that GitHub could auto-close issues. I will have to use the suggested format more often.

File: src/js/control-bar/volume-control/volume-bar.js (hunk 2 above)
Comment (BrandonOCasey) [inline src/js/control-bar/volume-control/volume-bar.js]: changed to toString()

File: src/js/control-bar/volume-control/volume-bar.js [hunk 3]
```diff
@@ -106,7 +106,7 @@ class VolumeBar extends Slider {
    */
   updateARIAAttributes(event) {
     // Current value of volume bar as a percentage
-    const volume = (this.player_.volume() * 100).toFixed(2);
+    const volume = (this.player_.volume() * 100).toString();
```
Comment (gkatsev) [inline src/js/control-bar/volume-control/volume-bar.js]: I think we'd still want Math.round or Math.floor to make sure we are getting an integer.

Comment (BrandonOCasey) [inline src/js/control-bar/volume-control/volume-bar.js]: Done
