### PR TITLE
fix: Remove img el when there's no poster source

### LINKED ISSUE #8122: [v8] Empty `src` attribute of the `img` element when no poster is added
### Description

[The poster is set to an empty string](https://github.com/videojs/video.js/blob/v8.0.4/src/js/player.js#L433) if no poster is initially configured. Which causes that empty string to be set for `src` of the `img` element of the poster. Which is invalid HTML according to HTML-validators.

### Reduced test case

_No response_

### Steps to reproduce

Check the description for an explanation.

### Errors

_No response_

### What version of Video.js are you using?

8.0.4

### Video.js plugins used.

_No response_

### What browser(s) including version(s) does this occur with?

110

### What OS(es) and version(s) does this occur with?

Linux

### PR DESCRIPTION
**Pull request by mister-ben**
## Description
If there is no poster source, an img el can't be present as it would be invalid.

## Specific Changes proposed
Use a div (again) as the top level element of the PosterImage, to keep position in the DOM. Insert/remove the picture/img els when a poster source is set/unset. 
Fixes #8122 

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [x] Change has been verified in an actual browser (Chrome, Firefox, IE)
  - [x] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

File: src/js/poster-image.js [hunk 1]
```diff
@@ -131,7 +138,7 @@ class PosterImage extends ClickableComponent {
    *        The URL to the source for the `PosterImage`.
    */
   setSrc(url) {
-    this.el_.querySelector('img').src = url;
+    this.$('img').src = url;
```
Comment (gkatsev) [inline src/js/poster-image.js:141]: this will throw if someone tries to set a src and the img element isn't present.

File: src/js/poster-image.js [hunk 2]
```diff
@@ -113,13 +101,32 @@ class PosterImage extends ClickableComponent {
...
     const url = this.player().poster();
 
-    this.setSrc(url);
-
-    // If there's no poster source we should display:none on this component
-    // so it's not still clickable or right-clickable
     if (url) {
+      // As there's a poster source, add a picture/img if not already present
+
+      if (!this.$('img')) {
```
Comment (gkatsev) [inline src/js/poster-image.js:107]: this probably should move into `setSrc` so that either update or setSrc can be called without any errors. And it'll keep this method the same.

File: src/js/poster-image.js (hunk 1 above)
Comment (mister-ben) [reply src/js/poster-image.js:141]: I was thinking a poster is only set with `player.poster('...')`, but you're right of course; `setSrc()` isn't "private" so does need to work independently of `update()`.

**Review by gkatsev — APPROVED** [review]
