### PR TITLE
fix: Don't request fullscreen from document PIP window

### LINKED ISSUE #8877: Double clicking document PiP window produces an error "Uncaught (in promise) TypeError: Fullscreen is not supported"
### Description

When the document picture-in-picture window is open, double clicking in it produces an error "Uncaught (in promise) TypeError: Fullscreen is not supported".

### Reduced test case

https://videojs.com/city

### Steps to reproduce

1. Open https://videojs.com/city in Chrome or Edge
2. Activate picture-in-picture
3. Double click in PiP window
4. In the console an erro is shown "Uncaught (in promise) TypeError: Fullscreen is not supported"

### Errors

video.es.js:26045 Uncaught (in promise) TypeError: Fullscreen is not supported
    at An.requestFullscreenHelper_ (video.es.js:26045:44)
    at video.es.js:26016:28
    at new Promise (<anonymous>)
    at An.requestFullscreen (video.es.js:25998:12)
    at An.handleTechDoubleClick_ (video.es.js:25039:16)
    at An.boundHandleTechDoubleClick_ (video.es.js:23420:50)
    at s.dispatcher.s.dispatcher (video.es.js:2511:31)

### What version of Video.js are you using?

Latest

### Video.js plugins used.

_No response_

### What browser(s) including version(s) does this occur with?

Chrome 129, Edge 129

### What OS(es) and version(s) does this occur with?

Windows, Linux, MacOS

### PR DESCRIPTION
**Pull request by mister-ben**
## Description
Double clicking the document pip window requests fullscreen but this fails. The gesture on the pip window can't initiate fullscreen.
Fixes #8877

## Specific Changes proposed
Change the default double click action to just exit pip. This is the same behaviour as before without the error, as requestFullScreen() calls exitPictureInPicture();

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [x] Change has been verified in an actual browser (Chrome, Firefox, IE)
  - [x] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
  - [x] Has no DOM changes which impact accessiblilty or trigger warnings (e.g. Chrome issues tab)
  - [x] Has no changes to JSDoc which cause `npm run docs:api` to error
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

File: src/js/player.js [hunk 1]
```diff
@@ -2045,7 +2046,12 @@ class Player extends Component {
         ) {
 
           this.options_.userActions.doubleClick.call(this, event);
-
+        } else if (this.isInPictureInPicture() && !document.pictureInPictureElement) {
+          // Checking the presence of `window.documentPictureInPicture.window` complicates
+          // tests, checking `document.pictureInPictureElement` also works. It wouldn't
+          // be null in  regular picture in picture.
```
Comment (gkatsev) [inline src/js/player.js:2052]: nit:
```suggestion
          // be null in regular picture in picture.
```
