### PR TITLE
fix: force autoplay in Chrome

### LINKED ISSUE #4720: Autoplay not working on chrome, videojs 6.4.0 / chrome 62.0.3202.75 (Works on Firefox / Edge)
## Description
Using the latest 6.4.0 js and css the autoplay doesn't work only on chrome, tested on firefox / edge and it work. Also videojs 5 autoplay does work, so it seems to be a problem related to version 6.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Load latest JS / CSS 6.4.0
2. Print the player
(example)             <video id='video' class="video-js vjs-fluid" data-setup='{ "controls": true, "autoplay": true, "preload": "auto" }' width="600" height="337" poster="<?=$config->thumbUrl?>/<?=$video->filename?>.jpg?i=<?php echo time(); ?>">
3. try all 3 browsers
-Chrome
-Edge
-Firefox

## Results
Chrome - No Autoplay
Edge - Autoplays
Firefox - Autoplays
### Expected
Chrome - Autoplays
Edge - Autoplays
Firefox - Autoplays

### Actual
autoplay doesn't work

### Error output
none

## Additional Information
Video js version 5 does autoplay correctly
#### videojs
6.4.0 / 6.2.8 tested
#### browsers
chrome
#### OSes
windows
### plugins
none

### PR DESCRIPTION
**Pull request by gkatsev**
Chrome has started pausing autoplaying video elements when they are
moved in the DOM. Here we need to make sure that if the video started
autoplaying, after we move the element in the DOM we call play again.

Fixes #4720.

### CODE REVIEW

File: src/js/tech/html5.js [hunk 1]
```diff
@@ -329,6 +333,7 @@ class Html5 extends Tech {
       }
     }
 
+    this.hasStartedPlayback_ = el.paused;
```
Comment (mister-ben) [inline src/js/tech/html5.js]: `el.paused`, is also true if it's never played.

Comment (gkatsev) [reply src/js/tech/html5.js]: yup, this should actually be `!el.paused`. Also @andriybohdan tested it and found that it just autoplayed everything, probably because of this.

Comment (mister-ben) [reply src/js/tech/html5.js]: I think this might also be too late to check anyway. The element would be moved and apparently paused at https://github.com/videojs/video.js/blob/master/src/js/player.js#L643.

What is the disadvantage to creating a new video el as we do for iphone?

Comment (gkatsev) [reply src/js/tech/html5.js]: Recreating the element in all conditions could potentially be a breaking change.
However, it'll be something to consider if this type of workaround wouldn't work.

Comment (gkatsev) [reply src/js/tech/html5.js]: Also, I think this place is fine because we set the `autoplay` attribute a few lines above. Seems like `!el.paused` seems to work here but I guess we'd want to do more tests before pulling it in.

**Comment by gkatsev** [comment]
Looks like getting the conditional right also fixed the tests :)

**Comment by gkatsev** [comment]
Seems like doing the check here isn't good enough. Seems like there are two options:
1. call play if autoplay is set, or
1. recreate the video element.
Option 1 isn't great because we had just removed code like this. Might be ok if we check for chrome and autoplay and we aren't playing already at the end of video.js initialization.
Option 2 isn't great because it's potentially a breaking change. I've seen too much code create video.js players but then proceed to call play and what not on the video element itself.

**Comment by pagarwal123** [comment]
QA-LGTM
