### PR TITLE
fix: try again on volume feature detection on iOS

### LINKED ISSUE #7040: Can't set volume when using iPhone without full screen
## Description
When I use **iPhone** to watch videojs player on all browsers like chrome, safari, etc.  I **can** set volume when player is full screen, but I **can't** set volume when player is **NOT** full screen. I can't drag and drop the dot on volume bar to set volume. It always stay at default volume. **Android** phone can set volume smoothly. Whether it is full screen or not full screen

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. use iPhone and go to videojs official demo: https://videojs.com/advanced/?video=disneys-oceans
2. try to set volume, and you can't set volume.

### PR DESCRIPTION
**Pull request by gkatsev**
On latest iOS, we are seeing times when the volume feature detection is
showing that we are able to change the volume, though, that is not the
case. Instead, on iOS, when we detect that we can control the volume, we
set a short timer to retest and reset the featuresVolumeControl property.

Fixes #7040

### CODE REVIEW

File: src/js/tech/html5.js [hunk 1]
```diff
@@ -1032,7 +1032,20 @@ Html5.canControlVolume = function() {
...
-    return volume !== Html5.TEST_VID.volume;
+
+    const canControl = volume !== Html5.TEST_VID.volume;
+
+    // on latest iOS, there are cases where we read the volume as changed.
+    // In those cases, we should add a timeout and check again later.
+    // Since features doesn't currently work asynchronously,
+    // we then have to manually set the new value.
+    if (canControl && browser.IS_IOS) {
+      setTimeout(() => {
```
Comment (misteroneill) [inline src/js/tech/html5.js:1043]: I don't have a strong opinion on this, but should this use `window.setTimeout` instead?

Comment (gkatsev) [reply src/js/tech/html5.js:1043]: oops, technically yes.

Comment (gkatsev) [reply src/js/tech/html5.js]: updated

File: src/js/tech/html5.js [hunk 2]
```diff
@@ -1032,7 +1032,20 @@ Html5.canControlVolume = function() {
...
 
     Html5.TEST_VID.volume = (volume / 2) + 0.1;
-    return volume !== Html5.TEST_VID.volume;
+
+    const canControl = volume !== Html5.TEST_VID.volume;
+
+    // on latest iOS, there are cases where we read the volume as changed.
+    // In those cases, we should add a timeout and check again later.
+    // Since features doesn't currently work asynchronously,
+    // we then have to manually set the new value.
```
[the remark this answers is not in the document]
Comment (gkatsev) [reply src/js/tech/html5.js:1041]: Sounds good to me.

[the remark this answers is not in the document]
Comment (gkatsev) [reply src/js/tech/html5.js]: Updated it manually to adjust positioning

**Review by gesinger — APPROVED** [review]
