### PR TITLE
perf: Fix memory leaks in safari, edge, and ie

### LINKED ISSUE #5878: Investigate dom data usage in tests on Safari, Edge, and IE
In https://github.com/videojs/video.js/pull/5862, we added a test that verifies that dom data is cleared out when a player is disposed. Due to time constraints, we weren't able to look at why Safari, Edge, and IE fail this test. Instead, we denylisted them for the test.
We should re-enable the tests on these browsers and investigate why they are failing.

### PR DESCRIPTION
**Pull request by BrandonOCasey**
## Description
* These where caused because we were not always able to clean up `resize` on the `ResizeManager`s iframe contentWindow after
* Native tracks on safari do not have an `off` so we have to remove our event listeners manually.

Fixes #5878

### CODE REVIEW

File: src/js/resize-manager.js [hunk 1]
```diff
@@ -71,7 +71,18 @@ class ResizeManager extends Component {
...
+        let unloadListener_ = this.unloadListener_ = function() {
+          Events.off(this, 'resize', debouncedHandler_);
+          Events.off(this, 'unload', unloadListener_);
+
+          unloadListener_ = null;
+        };
+
+        // safari and edge can unload the iframe before resizemanager dispose
+        // we have to dispose of event handlers correctly before that happens
+        Events.on(this.el_.contentWindow, 'unload', unloadListener_);
```
Comment (BrandonOCasey) [inline src/js/resize-manager.js]: We have to listen to the content window `unload` event so that we always dispose the iframe correctly if we add events to it. We also make sure to use the `context` of the `contentWindow` as `this` since IE11 does not work any other way for some reason.

File: test/unit/tracks/text-track-list-converter.test.js [hunk 2]
```diff
@@ -140,6 +140,9 @@ if (Html5.supportsNativeTextTracks()) {
     c.jsonToTextTracks(cleanup(c.textTracksToJson(tech)), tech);
 
     assert.equal(addRemotes, 2, 'we added two text tracks');
+
+    tt.removeTrack(nativeTrack.track);
```
Comment (BrandonOCasey) [inline test/unit/tracks/text-track-list-converter.test.js]: This test was leaking but only run on safari

File: test/unit/tracks/text-tracks.test.js [hunk 3]
```diff
@@ -272,12 +272,11 @@ if (Html5.supportsNativeTextTracks()) {
       assert.equal(emulatedTt.length, tt.length, 'we have matching tracks length');
       assert.equal(emulatedTt.length, 1, 'we have one text track');
 
-      emulatedTt.off('addtrack', addtrack);
       el.removeChild(track);
     };
 
-    emulatedTt.on('addtrack', addtrack);
-    emulatedTt.on('removetrack', function() {
+    emulatedTt.one('addtrack', addtrack);
```
Comment (BrandonOCasey) [inline test/unit/tracks/text-tracks.test.js]: This test was leaking but only run on safari

File: test/unit/utils/dom-data.test.js [hunk 4]
```diff
@@ -60,6 +56,7 @@ QUnit.done(function(details) {
   QUnit.test('Memory is not leaking', function(assert) {
     if (Object.keys(DomData.elData).length > 0) {
       videojs.domData = DomData;
+      window.videojs = videojs;
```
Comment (BrandonOCasey) [inline test/unit/utils/dom-data.test.js]: It seems that videojs isn't always on `window`

File: src/js/resize-manager.js [hunk 5]
```diff
@@ -120,12 +131,8 @@ class ResizeManager extends Component {
       this.resizeObserver_.disconnect();
     }
 
-    if (this.el_ && this.el_.contentWindow) {
-      Events.off(this.el_.contentWindow, 'resize', this.debouncedHandler_);
-    }
-
-    if (this.loadListener_) {
```
Comment (gkatsev) [inline src/js/resize-manager.js]: we should keep this around, while unlikely, it is still possible that dispose happens before the the loadListener is triggered.

Comment (gkatsev) [reply src/js/resize-manager.js]: Or does this end up being cleaned up automatically? If so, maybe it doesn't need to be stored on `this` but just as a local variable?

Comment (BrandonOCasey) [reply src/js/resize-manager.js]: I think anything on `this` is cleaned up automatically, but I did not intend to remove this, let me fix it.

File: src/js/tracks/audio-track-list.js [hunk 6]
```diff
@@ -72,22 +72,34 @@ class AudioTrackList extends TrackList {
       return;
     }
 
+    if (!this.enabledChange_) {
+      this.enabledChange_ = () => {
```
Comment (gkatsev) [inline src/js/tracks/audio-track-list.js]: looks like this change causes the first track to always get selected because we aren't changing it when new tracks come in. https://github.com/videojs/video.js/issues/5887

Probably similar issue in video tracks and text tracks.
