### PR TITLE
Deprecate the use of `starttime` in player.js

### LINKED ISSUE #3781: does the starttime/startTime option work? Do we want to keep it?
## Description
Right now I see an option for start time referenced in a few places under two different names. I am thinking that it is a legacy option that probably does not work anymore. Do we want to make it work again, or fix the option?

Code Links: 
* [starttime](https://github.com/videojs/video.js/blob/master/src/js/player.js#L1023)
* [startTime](https://github.com/videojs/video.js/blob/master/src/js/player.js#L657)?

### PR DESCRIPTION
**Pull request by BrandonOCasey**
## Description
Deprecate the use of `starttime` in player.js. It seems like the `startTime` option is actually used in flash so for the time being that will have to stay. Fixes #3781 

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [x] If necessary, more likely in a feature request than a bug fix
  - [x] Change has been verified in an actual browser (Chome, Firefox, IE)
  - [x] Unit Tests updated or fixed
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

File: src/js/player.js [hunk 1]
```diff
@@ -1271,12 +1271,14 @@ class Player extends Component {
    *
    * @fires Player#firstplay
    * @listens Tech#firstplay
+   * @deprecated In 6.0 passing the `starttime` option to the player will be deprecated
```
Comment (misteroneill) [inline src/js/player.js]: Rather than "In 6.0" I wonder if we can phrase this as "As of 6.0"?

Comment (BrandonOCasey) [inline src/js/player.js]: seems like a good idea

**Comment by gkatsev** [comment]
I think this one can be merged in as a minor.
