### PR TITLE
fix: use guid to ensure uniqueness of track setting options

### LINKED ISSUE #8761: More duplicate HTML IDs
### Description

After updating from `8.12.0` to `8.15.0` I started getting more duplicate ID errors from my HTML validator.

### Reduced test case

N/A

### Steps to reproduce

The duplicate IDs that the validator gives are: `-50`, `-75`, `-100`, `-125`, `-150`, `-175`, `-200`, `-300`, `-400`, `-None`, `-Raised`, `-Depressed`, `-Uniform`, `-Dropshadow`, `-ProportionalSansSerif`, `-MonospaceSansSerif`, `-ProportionalSerif`, `-MonospaceSerif`, `-Casual`, `-Script`, `-SmallCaps`. The first one, for example, I see here:

```html
<div class="vjs-track-settings-font"><fieldset class="vjs-font-percent vjs-track-setting"><legend id="captions-font-size-vjs_video_2739_component_3312">Font Size</legend><select id="vjs_select_3389" aria-labelledby="captions-font-size-vjs_video_2739_component_3312"><option id="-50" value="0.50" aria-labelledby="captions-font-size-vjs_video_2739_component_3312 -50">50%</option>
```

I have a second video in the page so I guess that's why there are two of these.

### Errors

_No response_

### What version of Video.js are you using?

8.15.0

### Video.js plugins used.

_No response_

### What browser(s) including version(s) does this occur with?

Chromium

### What OS(es) and version(s) does this occur with?

Linux

### PR DESCRIPTION
**Pull request by mister-ben**
The fix for the previous issue with the new text track settings introduced that ids would be re-used across players as there was no prefix for the settings that don't have a `<label>` for their `<select>`.

This change uses a generated guid for items without that label.
Fixes #8761

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [x] Change has been verified in an actual browser (Chrome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
  - [x] Has no DOM changes which impact accessiblilty or trigger warnings (e.g. Chrome issues tab)
  - [x] Has no changes to JSDoc which cause `npm run docs:api` to error
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

File: src/js/tracks/text-track-select.js [hunk 1]
```diff
@@ -29,11 +30,10 @@ class TextTrackSelect extends Component {
    * @param {string} [options.id]
    *        A text with part of an string to create atribute of aria-labelledby.
    *
-   * @param {array} [options.SelectOptions]
+   * @param {Array} [options.SelectOptions]
    *        Array that contains the value & textContent of for each of the
    *        options elements.
    */
-
```
Comment (mister-ben) [inline src/js/tracks/text-track-select.js:36]: Unrelated to issue, resolving jsdoc warnings from lint.

**Review by gkatsev — APPROVED** [review]
