### PR TITLE
fix(types): Fix issues in exported types

### LINKED ISSUE #8301: A number of TypeScript errors in the exported types
### Description

```
node_modules/video.js/dist/types/event-target.d.ts:9:13 - error TS2395: Individual declarations in merged declaration 'EventTarget' must be all exported or all local.

9 export type EventTarget = () => any;
              ~~~~~~~~~~~

node_modules/video.js/dist/types/event-target.d.ts:18:15 - error TS2395: Individual declarations in merged declaration 'EventTarget' must be all exported or all local.

18 declare class EventTarget {
                 ~~~~~~~~~~~

node_modules/video.js/dist/types/plugin.d.ts:5:13 - error TS2395: Individual declarations in merged declaration 'Plugin' must be all exported or all local.

5 export type Plugin = {
              ~~~~~~

node_modules/video.js/dist/types/plugin.d.ts:35:15 - error TS2395: Individual declarations in merged declaration 'Plugin' must be all exported or all local.

35 declare class Plugin {
                 ~~~~~~

node_modules/video.js/dist/types/tech/tech.d.ts:5:13 - error TS2395: Individual declarations in merged declaration 'Tech' must be all exported or all local.

5 export type Tech = any | string;
              ~~~~

node_modules/video.js/dist/types/tech/tech.d.ts:12:15 - error TS2395: Individual declarations in merged declaration 'Tech' must be all exported or all local.

12 declare class Tech extends Component {
                 ~~~~

node_modules/video.js/dist/types/tech/tech.d.ts:239:15 - error TS2552: Cannot find name 'TimeRange'. Did you mean 'TimeRanges'?

239     played(): TimeRange;
                  ~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:22227:13
    22227 declare var TimeRanges: {
                      ~~~~~~~~~~
    'TimeRanges' is declared here.

node_modules/video.js/dist/types/tracks/audio-track-list.d.ts:15:26 - error TS2304: Cannot find name 'AudioTrack'.

15     constructor(tracks?: AudioTrack[]);
                            ~~~~~~~~~~

node_modules/video.js/dist/types/tracks/html-track-element.d.ts:8:15 - error TS2415: Class 'HTMLTrackElement' incorrectly extends base class 'EventTarget'.
  Property 'allowedEvents_' is private in type 'EventTarget' but not in type 'HTMLTrackElement'.

8 declare class HTMLTrackElement extends EventTarget {
                ~~~~~~~~~~~~~~~~

node_modules/video.js/dist/types/tracks/text-track-list.d.ts:17:5 - error TS2416: Property 'addTrack' in type 'TextTrackList' is not assignable to the same property in base type 'TrackList'.
  Type '(track: TextTrack) => void' is not assignable to type '(track: Track) => void'.
    Types of parameters 'track' and 'track' are incompatible.
      Type 'Track' is missing the following properties from type 'TextTrack': tech_, cues_, activeCues_, preload_, and 8 more.

17     addTrack(track: import('./text-track').default): void;
       ~~~~~~~~

node_modules/video.js/dist/types/tracks/text-track.d.ts:8:15 - error TS2415: Class 'TextTrack' incorrectly extends base class 'Track'.
  Property 'allowedEvents_' is private in type 'Track' but not in type 'TextTrack'.

8 declare class TextTrack extends Track {
                ~~~~~~~~~

node_modules/video.js/dist/types/tracks/track-list.d.ts:8:15 - error TS2415: Class 'TrackList' incorrectly extends base class 'EventTarget'.
  Types have separate declarations of a private property 'allowedEvents_'.

8 declare class TrackList extends EventTarget {
                ~~~~~~~~~

node_modules/video.js/dist/types/video.d.ts:88:14 - error TS2304: Cannot find name 'version'.

88     export { version as VERSION };
                ~~~~~~~
```

### Reduced test case

No need for a test case

### Steps to reproduce

Just install `video.js` and run a TypeScript check with this `tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "allowJs": false,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "Node",
    "useDefineForClassFields": true,
    "strict": true,
    "exactOptionalPropertyTypes": true,
    "noUncheckedIndexedAccess": true,
    "newLine": "lf",
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noEmitOnError": true,
    "noEmit": true,
    "verbatimModuleSyntax": true,
    "declaration": true,
    "declarationMap": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "baseUrl": ".",
    "module": "ESNext",
    "experimentalDecorators": true
  }
}
```

The only workaround is adding `"skipLibCheck": true`.

Perhaps related to https://github.com/videojs/video.js/issues/8141.

Happens on TypeScript 5.1.3 but most likely it happens also on older versions.

### Errors

_No response_

### What version of Video.js are you using?

8.3.0

### Video.js plugins used.

_No response_

### What browser(s) including version(s) does this occur with?

N/A

### What OS(es) and version(s) does this occur with?

Linux

### PR DESCRIPTION
**Pull request by boris-petrov**
## Description
Fixes #8301

## Specific Changes proposed
Fix exported types.

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Change has been verified in an actual browser (Chrome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Review by mister-ben — APPROVED** [review]
Looks good, thanks

**Review by Essk — APPROVED** [review]

File: src/js/video.js [hunk 1]
```diff
@@ -2,7 +2,7 @@
  * @file video.js
  * @module videojs
  */
-import {version} from '../../package.json';
+import packageJson from '../../package.json';
```
Comment (misteroneill) [inline src/js/video.js:5]: This causes the entire `package.json` to be inlined in the dist file(s):

```js
  var name = "video.js";
  var description = "An HTML5 video player that supports HLS and DASH with a common API and skin.";
  var version$6 = "8.5.0";
  var main = "./dist/video.cjs.js";
  var module = "./dist/video.es.js";
  var style = "./dist/video-js.css";
  var types = "./dist/types/video.d.ts";
  var copyright = "Copyright Brightcove, Inc. <https://www.brightcove.com/>";
  var license = "Apache-2.0";
  var keywords = [
  	"dash",
  	"hls",
  	"html5",
  	"player",
  	"video",
  	"videojs"
  ];
  var homepage = "https://videojs.com";
  var author = "Steve Heffernan";
  var scripts = {
  	sandbox: "node build/sandbox.js",
  	prestart: "npm-run-all sandbox",
  	start: "npm-run-all -p watch karma-server",
  	clean: "shx rm -rf ./dist ./test/dist ./docs/api ./lang/zh-Han*.json",
  	postclean: "shx mkdir -p ./dist/lang ./test/dist",
  	changelog: "conventional-changelog -p videojs -i CHANGELOG.md -s",
  	build: "npm-run-all build-dev minify copy zip",
  	"build-dev": "npm-run-all clean lint-errors build:js build:css build:lang build:test build:types",
  	"build:test": "npm-run-all build:test:*",
  	"build:test:a11y": "shx cp sandbox/descriptions.html.example sandbox/descriptions.test-a11y.html",
  	"build:test:browserify": "browserify test/require/browserify.js -o test/dist/browserify.js",
  	"build:test:webpack": "webpack --hide-modules test/require/webpack.js test/dist/webpack.js",
  	copy: "npm-run-all copy:*",
  	"copy:fonts": "shx cp -R node_modules/videojs-font/fonts dist/font",
  	"copy:examples": "shx cp -R docs/examples dist/",
  	"build:js": "rollup -c",
  	"build:css": "npm-run-all build:css:*",
  	"build:css:cdn": "sass --load-path='./' --load-path='./node_modules/' --no-source-map src/css/vjs-cdn.scss dist/alt/video-js-cdn.css",
  	"build:types": "tsc",
  	"postbuild:css:cdn": "postcss --verbose --config postcss.config.js -d dist/alt dist/alt/video-js-cdn.css",
  	"build:css:default": "sass --load-path='./' --load-path='./node_modules/' --no-source-map src/css/vjs.scss dist/video-js.css",
  	"postbuild:css:default": "postcss --verbose --config postcss.config.js -d dist/ dist/video-js.css",
  	"prebuild:lang": "npm-run-all -s prebuild:lang:*",
  	"prebuild:lang:chinese-s": "shx cp lang/zh-CN.json lang/zh-Hans.json",
  	"prebuild:lang:chinese-t": "shx cp lang/zh-TW.json lang/zh-Hant.json",
  	"build:lang": "vjslang --dir dist/lang",
  	"postbuild:lang": "shx cp -R lang/* dist/lang/",
  	minify: "npm-run-all minify:*",
  	"minify:js": "node build/minify.js",
  	"minify:css": "npm-run-all minify:css:*",
  	"minify:css:cdn": "cleancss dist/alt/video-js-cdn.css -o dist/alt/video-js-cdn.min.css",
  	"minify:css:default": "cleancss dist/video-js.css -o dist/video-js.min.css",
  	watch: "npm-run-all -p watch:*",
  	"watch:lang": "chokidar --initial \"lang/**/!(zh-Hans|zh-Hant)*.json\" -c \"npm run build:lang\"",
  	"watch:rollup": "rollup -c -w --no-progress",
  	"watch:types": "tsc -w",
  	"watch:css": "npm-run-all -p build:css:default build:css:cdn watch:css:*",
  	"watch:css:default": "npm run build:css:default -- --watch",
  	"watch:css:cdn": "npm run build:css:cdn -- --watch",
  	assets: "node build/assets.js",
  	lint: "vjsstandard",
  	"lint-errors": "vjsstandard --errors",
  	"karma-server": "karma start test/karma.conf.js --singleRun=false --auto-watch",
  	posttest: "[ \"$CI_TEST_TYPE\" != 'coverage' ] || shx cat test/dist/coverage/text.txt",
  	pretest: "npm run build-dev",
  	test: "npm-run-all -p test:*",
  	"test:node-require": "node test/require/node.js",
  	"test:a11y": "node build/test-a11y.js",
  	"test:unit": "karma start test/karma.conf.js",
  	docs: "npm-run-all clean docs:lint docs:api",
  	"docs:api": "node ./build/doc-version.js && jsdoc -c .jsdoc.json",
  	"postdocs:api": "node ./build/fix-api-docs.js",
  	"docs:lint": "remark -- './{,!(node_modules)/**/}!(CHANGELOG)*.md'",
  	"docs:fix": "remark --output -- './{,!(node_modules)/**/}!(CHANGELOG)*.md'",
  	"docs:lang": "node build/translations.js",
  	netlify: "node ./build/netlify.js",
  	"netlify-docs": "node ./build/netlify-docs.js",
  	prepublishOnly: "run-p build",
  	version: "is-prerelease || npm run changelog && git add CHANGELOG.md",
  	zip: "cd dist && cross-env bestzip \"./video-js-${npm_package_version}.zip\" * && cd .."
  };
  var repository = {
  	type: "git",
  	url: "https://github.com/videojs/video.js.git"
  };
  var dependencies = {
  	"@babel/runtime": "^7.12.5",
  	"@videojs/http-streaming": "3.3.1",
  	"@videojs/vhs-utils": "^4.0.0",
  	"@videojs/xhr": "2.6.0",
  	"aes-decrypter": "^4.0.1",
  	global: "4.4.0",
  	keycode: "2.2.0",
  	"m3u8-parser": "^6.0.0",
  	"mpd-parser": "^1.0.1",
  	"mux.js": "^6.2.0",
  	"safe-json-parse": "4.0.0",
  	"videojs-contrib-quality-levels": "4.0.0",
  	"videojs-font": "4.1.0",
  	"videojs-vtt.js": "0.15.4"
  };
  var devDependencies = {
  	"@babel/core": "^7.9.0",
  	"@babel/plugin-transform-runtime": "^7.9.0",
  	"@babel/preset-env": "^7.9.0",
  	"@rollup/plugin-image": "^3.0.2",
  	"@rollup/plugin-replace": "^2.4.1",
  	"@types/node": "^18.8.3",
  	"access-sniff": "^3.2.0",
  	autoprefixer: "^10.2.5",
  	bestzip: "^2.2.0",
  	browserify: "^16.2.3",
  	"chokidar-cli": "^2.1.0",
  	"clean-css-cli": "^4.3.0",
  	"clean-jsdoc-theme": "^4.2.1",
  	"cli-table": "^0.3.1",
  	"conventional-changelog-cli": "^2.0.21",
  	"conventional-changelog-videojs": "^3.0.1",
  	"cross-env": "^7.0.3",
  	"es5-shim": "^4.5.15",
  	"es6-shim": "^0.35.6",
  	filesize: "^4.1.2",
  	"gh-release": "^6.0.4",
  	"humanize-duration": "^3.26.0",
  	husky: "^1.3.1",
  	"is-ci": "^3.0.0",
  	jsdoc: "^3.6.11",
  	"jsdoc-tsimport-plugin": "^1.0.5",
  	karma: "^6.4.0",
  	"lint-staged": "^10.5.4",
  	"markdown-table": "^1.1.3",
  	maxmin: "^2.1.0",
  	"not-prerelease": "^1.0.1",
  	"npm-merge-driver-install": "^2.0.1",
  	"npm-run-all": "^4.1.5",
  	postcss: "^8.2.13",
  	"postcss-cli": "^8.3.1",
  	qunit: "2.13.0",
  	"remark-cli": "^6.0.1",
  	"remark-lint": "^6.0.6",
  	"remark-parse": "^6.0.3",
  	"remark-stringify": "^6.0.4",
  	"remark-toc": "^5.1.1",
  	"remark-validate-links": "^8.0.2",
  	replace: "^1.2.1",
  	rollup: "^2.2.0",
  	"rollup-plugin-alias": "^1.5.2",
  	"rollup-plugin-babel": "^4.4.0",
  	"rollup-plugin-commonjs": "^9.3.4",
  	"rollup-plugin-external-globals": "^0.6.1",
  	"rollup-plugin-ignore": "^1.0.5",
  	"rollup-plugin-istanbul": "^3.0.0",
  	"rollup-plugin-json": "^3.1.0",
  	"rollup-plugin-multi-entry": "^2.0.2",
  	"rollup-plugin-node-resolve": "^4.2.4",
  	"rollup-plugin-progress": "^1.1.2",
  	"rollup-plugin-stub": "^1.2.0",
  	"rollup-plugin-svg": "^2.0.0",
  	sass: "^1.34.0",
  	semver: "^5.7.0",
  	shelljs: "^0.8.5",
  	shx: "^0.3.2",
  	sinon: "^11.1.1",
  	typescript: "^4.8.4",
  	"uglify-js": "^3.6.0",
  	unified: "^7.0.2",
  	"videojs-generate-karma-config": "^8.0.1",
  	"videojs-languages": "^2.0.0",
  	"videojs-standard": "^9.0.1",
  	webpack: "^1.15.0"
  };
  var vjsstandard = {
  	ignore: [
  		"dist",
  		"docs",
  		"sandbox",
  		"test/dist",
  		"test/api",
  		"core.js",
  		"core.es.js"
  	]
  };
  var husky = {
  	hooks: {
  		"pre-commit": "lint-staged"
  	}
  };
  var packageJson = {
  	name: name,
  	description: description,
  	version: version$6,
  	main: main,
  	module: module,
  	style: style,
  	types: types,
  	copyright: copyright,
  	license: license,
  	keywords: keywords,
  	homepage: homepage,
  	author: author,
  	scripts: scripts,
  	repository: repository,
  	dependencies: dependencies,
  	devDependencies: devDependencies,
  	vjsstandard: vjsstandard,
  	husky: husky,
  	"lint-staged": {
  	"*.js": [
  		"vjsstandard --fix"
  	],
  	"!(CHANGELOG)*.md": [
  		"remark --output --"
  	],
  	"lang/**/!(zh-Hans|zh-Hant)*.json": [
  		"node build/translations.js"
  	]
  }
  };
```

File: src/js/tracks/audio-track-list.js [hunk 2]
```diff
@@ -36,7 +36,7 @@ class AudioTrackList extends TrackList {
   /**
    * Create an instance of this class.
    *
-   * @param {AudioTrack[]} [tracks=[]]
+   * @param { import('./audio-track').default[] } [tracks=[]]
```
Comment (misteroneill) [inline src/js/tracks/audio-track-list.js:39]: I think I'm okay with these kinds of changes as a temporary fix to make TypeScript work, but I have to admit that I'm concerned that it makes the documentation comments and (in some cases) may make the rendered API docs less useful.

We should find a better way to implement TypeScript compatibility for the long-term.

**Review by misteroneill — CHANGES_REQUESTED** [review]
I don't think we can merge this because it adds a lot of unnecessary data to the `dist` file(s).

File: src/js/video.js (hunk 1 above)
Comment (boris-petrov) [reply src/js/video.js:5]: hm, right. Any ideas how to prevent that and still have correct types?

Comment (boris-petrov) [reply src/js/video.js]: I changed it to just adding a type-declaration. Can you double-check that this fixes the issue? Thanks!

File: src/js/tracks/audio-track-list.js (hunk 2 above)
Comment (boris-petrov) [reply src/js/tracks/audio-track-list.js:39]: The best way would be to rewrite `video,js` in TypeScript. :smile:

**Review by mister-ben — APPROVED** [review]
I think this is OK now, the unnecessary junk from package.json isn't being added. With this and #8218 we should be in a slightly better place wrt types.

**Comment by drallgood** [comment]
Is it possible to merge this soon?
Without it I can't use this library and I would really like to

**Comment by qstiegler** [comment]
Please merge this soon!

**Comment by andreifilip123** [comment]
I'd also appreciate if this would be merged soon 🙏 Currently, we have to do a bunch of @ts-ignore for types we know are correct. Thank you 🙏

**Review by dzianis-dashkevich — APPROVED** [review]

**Review by Essk — APPROVED** [review]

**Review by misteroneill — APPROVED** [review]

**Comment by dzianis-dashkevich** [comment]
@boris-petrov 
Thank you for your contribution!

**Comment by pmev0** [comment]
hi can you fix this for React too? i cannot install with npm run build in vite.. i use latest videojs version
