### PR TITLE
Use passive event listeners for touchstart/touchmove

### LINKED ISSUE #4432: Chrome Violation: Non-passive scroll handlers
## Description
Chrome is logging "Violations" for videojs's scroll handlers.

```
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
external_embed-b5b3e31….js:936
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
```

Related Links:
https://developers.google.com/web/updates/2016/06/passive-event-listeners
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Safely_detecting_option_support

## Steps to reproduce
1. Open Chrome and dev tools
2. Set console level to "Verbose"
3. Go to http://videojs.com
4. Look in the console for "Violation" warnings.

### Expected
Videojs should add `passive: true` when adding event listeners, so Chrome (and others) can be more performant.  The Violation warnings should go away as well.

### Actual
Violation warnings in the dev tools console.

#### videojs
5.19.2
#### browsers
Chrome Version 59.0.3071.109 (Official Build) (64-bit)
#### OSes
I tested on mac
### plugins
No

### PR DESCRIPTION
**Pull request by mister-ben**
## Description
Not using passive event listeners now causes Chrome to log warnings to the console, and possibly has a performance impact
Fixes #4432

## Specific Changes proposed
Where supported, use passive event listeners for `touchmove` and `touchstart` 

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [x] If necessary, more likely in a feature request than a bug fix
  - [x] Change has been verified in an actual browser (Chome, Firefox, IE)
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

File: src/js/utils/events.js [hunk 1]
```diff
@@ -273,7 +290,13 @@ export function on(elem, type, fn) {
 
   if (data.handlers[type].length === 1) {
     if (elem.addEventListener) {
-      elem.addEventListener(type, data.dispatcher, false);
+      let options = false;
+
+      if (_supportsPassive &&
+        ['touchstart', 'touchmove'].indexOf(type) > -1) {
```
Comment (misteroneill) [inline src/js/utils/events.js]: I wonder if this array ought to be defined once in the parent scope rather than inline. Something like:

```js
const passiveEvents = [
  'touchstart',
  'touchmove'
];
```

File: src/js/utils/events.js [hunk 2]
```diff
@@ -203,6 +203,31 @@ export function fixEvent(event) {
 }
 
 /**
+ * Whether passive event listeners are supported
+ */
+let _supportsPassive = false;
+
+try {
```
Comment (gkatsev) [inline src/js/utils/events.js]: we should wrap this try/catch in an iife.

**Comment by misteroneill** [comment]
Looks like this will fix #4432 (we should not that in the merge commit).

**Comment by gkatsev** [comment]
We probably should make this against 5.x as well.
