### PR TITLE
fix: keep focus trapping contained to modal

### LINKED ISSUE #6950: Focus Not Trapped in Caption Settings Dialog
## Description
The dialog used for Closed Captioning settings does not trap focus within the dialog contents. 

It seems like this was meant to be fixed as part of #2746 / #4025.
> Keyboard focus is not trapped inside the dialog while it is open

## Steps to reproduce
1. Go to https://videojs.com/advanced/?video=elephantsdream
2. Tab to the Captions Menu
3. Enter the Caption Settings Dialog
4. Tab to the Close button.
5. Tab again.

### Expected
The focus is moved to the first element in the Caption Settings Menu

### Actual
The focus is moved outside of the video player.

### Error output
N/A

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Happens on 7.7.5 and 7.10.2 at least

#### browsers
Firefox, Chrome. Possibly others but untested.

#### OSes
Verified on MacBook Pro running MacOS Catalina 10.15.7

### plugins
Unsure

### PR DESCRIPTION
**Pull request by kannapples**
## Description

During an accessibility audit of a project I work on that uses VideoJS we received the following feedback about how focus trapping works in the closed caption settings modal. 

The dialog used for Closed Captioning settings does not trap focus when tabbing forward. This is because the close button has its own `handleKeyDown` method that pulls focus out of the modal container. 

Fixes #6950 

## Specific Changes proposed
The close button `handleKeyDown` won't call the parent `handleKeyDown` when a Tab key is pressed.

Also, the code to find the focusIndex in `modal-dialog.js` is unnecessarily complex. I've updated it to be more streamlined.

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [x] Change has been verified in an actual browser (Chrome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

File: src/js/modal-dialog.js [hunk 1]
```diff
@@ -461,19 +461,7 @@ class ModalDialog extends Component {
...
-      if (activeEl === focusableEls[i]) {
-        focusIndex = i;
-        break;
-      }
-    }
-
-    if (document.activeElement === this.el_) {
-      focusIndex = 0;
-    }
+    const focusIndex = focusableEls.indexOf(document.activeElement);
```
Comment (brandonocasey) [inline src/js/modal-dialog.js:464]: `indexOf` isn't supported on a `NodeList` in ie 11, so we won't be able to use it

**Review by brandonocasey — CHANGES_REQUESTED** [review]

File: src/js/modal-dialog.js (hunk 1 above)
Comment (gkatsev) [reply src/js/modal-dialog.js:464]: I'd also be wary of making a change here.
This was based on https://github.com/gdkraus/accessible-modal-dialog/blob/master/modal-window.js#L95-L109 and doing a change here would require testing across a bunch of browsers, and we don't really have the bandwidth to do that.

Comment (kannapples) [reply src/js/modal-dialog.js]: Makes sense. Changed it back!

**Comment by OwenEdwards** [comment]
@gkatsev and @brandonocasey - I traced this back up the chain of extended components, and I think this is the change that is causing the problem (from #5969):

https://github.com/videojs/video.js/commit/79eadac2523094bdbc61a782d4ad10b72176cbcd#diff-ce6686cfe1f15de2870aabfcafd7ef6dd227f49fe67a811acc51c88325755b77R1089-R1093

I think that, strictly-speaking, it's this `event.stopPropagation();` that shouldn't be applied to a Tab keypress, but I confess that I'm always a little confused by event propagation! Maybe @misteroneill has some thoughts?

**Comment by gkatsev** [comment]
Yeah, that makes sense. The quick fix would be to only stop propagation when it isn't tab that was pressed. Probably worth investigating if the stopPropagation there is necessary or if we can get rid of it there and move it further down the chain into the user actions so it's only called if we have a user action configured and is being triggered.

**Comment by kannapples** [comment]
Hi @gkatsev @OwenEdwards - I updated the code to stop propagation in all cases except when Tab is pressed. 

I did look into implementing this through user actions, but I'm not sure its worth the effort. Currently, `player.js` doesn't receive any keydowns from the modal because they are all being suppressed in `modal-dialog.js::handleKeyDown`. Also, the player action for tabbing would need to be created, as `options_.userActions` is undefined for key down actions. 

This PR has been open for 8 months, and I would love to get it merged. Is the easy fix acceptable to you guys? Anything else I can do to get this moving again?

**Comment by kannapples** [comment]
> Hi @gkatsev @OwenEdwards - I updated the code to stop propagation in all cases except when Tab is pressed.
> 
> I did look into implementing this through user actions, but I'm not sure its worth the effort. Currently, `player.js` doesn't receive any keydowns from the modal because they are all being suppressed in `modal-dialog.js::handleKeyDown`. Also, the player action for tabbing would need to be created, as `options_.userActions` is undefined for key down actions.
> 
> This PR has been open for 8 months, and I would love to get it merged. Is the easy fix acceptable to you guys? Anything else I can do to get this moving again?

Hi @gkatsev @OwenEdwards, any thoughts on this? How do I get this fix merged!

**Comment by kannapples** [comment]
> > Hi @gkatsev @OwenEdwards - I updated the code to stop propagation in all cases except when Tab is pressed.
> > I did look into implementing this through user actions, but I'm not sure its worth the effort. Currently, `player.js` doesn't receive any keydowns from the modal because they are all being suppressed in `modal-dialog.js::handleKeyDown`. Also, the player action for tabbing would need to be created, as `options_.userActions` is undefined for key down actions.
> > This PR has been open for 8 months, and I would love to get it merged. Is the easy fix acceptable to you guys? Anything else I can do to get this moving again?
> 
> Hi @gkatsev @OwenEdwards, any thoughts on this? How do I get this fix merged!

Hey @gkatsev @OwenEdwards, me again. Can you please respond with either an affirmative on my fix, or some feedback on what is missing? This is a small usability fix that makes videojs more accessible, and was called out as a problem by an accessibility review done on our application.

**Comment by kannapples** [comment]
> > > Hi @gkatsev @OwenEdwards - I updated the code to stop propagation in all cases except when Tab is pressed.
> > > I did look into implementing this through user actions, but I'm not sure its worth the effort. Currently, `player.js` doesn't receive any keydowns from the modal because they are all being suppressed in `modal-dialog.js::handleKeyDown`. Also, the player action for tabbing would need to be created, as `options_.userActions` is undefined for key down actions.
> > > This PR has been open for 8 months, and I would love to get it merged. Is the easy fix acceptable to you guys? Anything else I can do to get this moving again?
> > 
> > 
> > Hi @gkatsev @OwenEdwards, any thoughts on this? How do I get this fix merged!
> 
> Hey @gkatsev @OwenEdwards @brandonocasey, me again. Can you please respond with either an affirmative on my fix, or some feedback on what is missing? This is a small usability fix that makes videojs more accessible, and was called out as a problem by an accessibility review done on our application.

Hi @gkatsev @OwenEdwards @brandonocasey I would really love to stop doing this, but I wont until I get a response... Can you please respond with either an affirmative on my fix, or some feedback on what is missing? This is a small usability fix that makes videojs more accessible, and was called out as a problem by an accessibility review done on our application.

**Review by gkatsev — APPROVED** [review]
Verified locally. Unfortunately, it seems like the netlify builds didn't work because this branch is old compared to the upstream branch.

**Review by misteroneill — APPROVED** [review]
Thanks @gkatsev! Hey @kannapples, sorry for the lack of attention on your PR. Approved now, we'll get it in the next Video.js release.
