### PR TITLE
fix: focus play toggle from Big Play Btn on play

### LINKED ISSUE #2729: Movement of keyboard focus from the 'big play' button to the full control bar to support keyboard accessibility
A couple of changes would fix accessibility issues related to the 'big play' button:
1. When the big play button is activated using the keyboard, **focus should be moved** to the regular play button in the control bar
2. There should be some indication to screen reader users that only the big play button is available before playback is started, and that the full control bar will become available when play starts (or that it has become available once the big play button has been activated, but this is not an ideal solution because that is the point when audio from the video playback will start).

This is related to, but distinct from. #2156.

### PR DESCRIPTION
**Pull request by gkatsev**
If the control bar and playtoggle exist, focus the playtoggle after
triggering play via the keyboard from the Big Play Button.
If `play()` returns a promise, wait until it resolves to focus,
otherwise, use a setTimeout.

Fixes #2729

### CODE REVIEW

File: src/js/big-play-button.js [hunk 1]
```diff
@@ -34,7 +34,22 @@ class BigPlayButton extends Button {
...
    */
   handleClick(event) {
-    this.player_.play();
+    const playPromise = this.player_.play();
+
+    const cb = this.player_.getChild('controlBar');
+    const playToggle = cb && cb.getChild('playToggle');
+
+    if (!playToggle) {
+      return;
```
Comment (OwenEdwards) [inline src/js/big-play-button.js]: If there isn't a playToggle control, focus ought to move to either the player's `<div>`, or the `<video>` element, rather than just falling into a black hole! I guess the `<video>` element won't be there if the player uses a Flash tech, so the `<div>` makes sense.

Comment (gkatsev) [inline src/js/big-play-button.js]: We can focus on the tech.

Comment (OwenEdwards) [inline src/js/big-play-button.js]: Strictly, focus ought to move to something which is actionable, but it can move to something which isn't if pressing Tab from there will get the user to an actionable control (rather than, for example, the next focusable element _after_ the video.js player)

Comment (gkatsev) [inline src/js/big-play-button.js]: Makes sense, I'll just focus the player element and we can always tweak it in the future if we think there's something better.

Comment (gkatsev) [inline src/js/big-play-button.js]: Updated to focus on the player element in this case.

**Comment by richardbushell** [comment]
@gkatsev
As per #4039, could this be included in latest 5.x release too please...

**Comment by gkatsev** [comment]
@OwenEdwards @richardbushell ported over in https://github.com/videojs/video.js/pull/4132/

**Comment by richardbushell** [comment]
@gkatsev Terrific, thanks...
