### PR TITLE
fix(fs): make sure there's only one fullscreenchange event

### LINKED ISSUE #5685: player fullscreenchange firing twice
In browsers that support the unprefixed fullscreen API (FF 64+ GC71+), the fullscreenchange event is firing twice every time fullscreen is toggled.

https://jsfiddle.net/jbrhq4s1/1/

### PR DESCRIPTION
**Pull request by gkatsev**
Before the fullscreen API was un-prefixed, we listened to triggered a
`fullscreenchange` event on the player manually. This worked fine
because a prefixed `fullscreenchange` event was triggered on the player
element itself. But when it was unprefixed, we ended up with two events
now, the unprefixed event and the one we triggered.

Instead, we should listen the event the browser supports and re-trigger
it as the unprefixed event as necessary.

We also make sure that the handler gets calls when the document level
fullscreenchange handler gets called so that it is cancelled properly.

Fixes #5685.

### CODE REVIEW

File: src/js/player.js [hunk 1]
```diff
@@ -2557,12 +2569,8 @@ class Player extends Component {
         // If cancelling fullscreen, remove event listener.
         if (this.isFullscreen() === false) {
           Events.off(document, fsApi.fullscreenchange, documentFullscreenChange);
+          this.handleFullscreenChange_();
```
[the remark this answers is not in the document]
Comment (gkatsev) [reply src/js/player.js]: Yup, because this will get called from the document's handler, there's no event on the element itself.

[the remark this answers is not in the document]
Comment (misteroneill) [reply src/js/player.js]: Perfect. I thought that was the case.

**Comment by gkatsev** [comment]
Looks like this works great everywhere except IE11.

**Comment by gkatsev** [comment]
Firefox has problems with closing.

**Comment by gkatsev** [comment]
Playground: https://deploy-preview-5686--videojs-docs.netlify.com/test-example/

File: src/js/player.js [hunk 2]
```diff
@@ -524,7 +524,15 @@ class Player extends Component {
...
 
     this.one('play', this.listenForUserActivity_);
-    this.on('fullscreenchange', this.handleFullscreenChange_);
+
+    if (FullscreenApi.fullscreenchange) {
+      this.on(FullscreenApi.fullscreenchange, this.handleFullscreenChange_);
+
+      if (IE_VERSION) {
+        this.on(document, FullscreenApi.fullscreenchange, this.handleFullscreenChange_);
+      }
```
Comment (misteroneill) [inline src/js/player.js]: I assume IE does not trigger the previous listener at all? If it did, this would seem to have potential to call `handleFullscreenChange_` twice.

Comment (gkatsev) [reply src/js/player.js]: Yeah, as far as I can tell IE11 only triggers the document level event in my testing.

Comment (misteroneill) [reply src/js/player.js]: Cool. And I checked in IE11 and it works the same as other browsers.

**Comment by nackd** [comment]
I tried this on a lot of different browsers and devices, including GC and FF from before and after the move to unprefixed. It worked everywhere, except on Android and desktop Firefox before unprefixed, where the event didn't fire. Note that depending on the Android device, that might be the latest release available.

**Comment by gkatsev** [comment]
@nackd that is firefox on android? Also, thanks for checking!

**Comment by gkatsev** [comment]
Thanks! Yeah, it's likely the same issue. I'll take a look.

**Comment by gkatsev** [comment]
@nackd I just pushed a change (c026af80) that I think fixes older firefox, would you be able to give it a try again?

**Comment by nackd** [comment]
Sure, but only on Thursday, @gkatsev.

**Comment by gkatsev** [comment]
@nackd that's fine. We're more or less all on break for the week anyway :)

**Comment by gkatsev** [comment]
@nackd hope you had a good new year, did you have a chance to take a look at this PR? Thanks!

**Comment by nackd** [comment]
I was finally able to get to this and it seems to work great, be it prefixed, unprefixed, desktop or Android Firefox. Thanks a lot, @gkatsev!
