### PR TITLE
fix: don't always use fastSeek when available.

### LINKED ISSUE #6988: Seeking via tab on seekBar does not work properly on iOS
## Description
When seeking via tab on the seekBar, currentTime is not set correctly.
Player must be in fullscreen mode to see the problem. The problem occurs from version 7.9.0 and above.

video-js-7 9 0-not-working-properly

## Steps to reproduce

Tested on iOS iPad Simulator with iOS 13.7

Created two code pens:

### Working properly:
video.js v7.8.4
https://codepen.io/nimoatwoodway/full/NWRRRpo

### Working not properly:
video.js v7.11.0
https://codepen.io/nimoatwoodway/full/WNGGGEW

Open in fullscreen and tab on the seek bar. Then you will see the offset. In the codepen the offset is much smaller than in my example in the description but you can see it.

### LINKED ISSUE #7360: Dash fastSeek issue in safari
## Description
When in safari, we are encountering an issue where the progress bar does not work properly when using Dash. While playing the video, when we click in the progress bar and then click before the current time, the video playback stops and shows strange behaviour. I included a potential fix and reproduction steps here: https://codepen.io/MarcoTradecast/pen/ZEKoJYb. For the fix I disabled fastSeek only for safari, since fastSeek is also possible for Firefox.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Open https://codepen.io/MarcoTradecast/pen/ZEKoJYb in Safari.
2. Change/revert the code as described in the comment.
3. Play the video and click (no dragging) to around 70% percent of the video in the progress bar.
4. Now click near the beginning of the video in the progress bar (once again no dragging).

### Expected
The video should go back to the desired timestamp.

### Actual
Video playback stops and currentTime is not being updated. Play/pause button is also not responding anymore.

### Error output
There are no errors

#### videojs
7.13.3
#### browsers
Safari (in my case 14.1.1)
#### OSes
macOS Big Sur 11.4
### plugins
No additional plugins are being used in the example.

I hope this issue is clear enough to reproduce :-)

### PR DESCRIPTION
**Pull request by gkatsev**
We were always setting `scrubbing(true)` on mouse down. This means, that
we'd use `fastSeek` even when seeking while clicking, rather than only
when scrubbing.

The main fix involves knowing in `handleMouseMove` whether we were
called directly as a `mousemove` handler or whether it was called from
`handleMouseDown`. This means that when `handleMouseMove` is called via
`handleMouseDown` we can skip setting `scrubbing(true)` and only do it
when we are scrubbing directly.

Fixes #6988, fixes #7360

### CODE REVIEW

File: src/js/slider/slider.js [hunk 1]
```diff
@@ -180,7 +180,7 @@ class Slider extends Component {
     this.on(doc, 'touchmove', this.handleMouseMove_);
     this.on(doc, 'touchend', this.handleMouseUp_);
 
-    this.handleMouseMove(event);
+    this.handleMouseMove(event, true);
```
Comment (gesinger) [inline src/js/slider/slider.js:183]: If it's something we may consider for the future, it may be worth adding a TODO for splitting the seeking logic out of the mouse move handler and calling it separately from here.

File: src/js/control-bar/progress-control/seek-bar.js [hunk 2]
```diff
@@ -269,13 +268,19 @@ class SeekBar extends Slider {
...
    * @listens mousemove
    */
-  handleMouseMove(event) {
+  handleMouseMove(event, mouseDown) {
     if (!Dom.isSingleLeftClick(event)) {
       return;
     }
+
+    if (!mouseDown && !this.player_.scrubbing()) {
+      this.player_.scrubbing(true);
```
Comment (gesinger) [inline src/js/control-bar/progress-control/seek-bar.js:281]: It would be worth adding a test for this behavior.

Comment (gkatsev) [reply src/js/control-bar/progress-control/seek-bar.js:281]: At first, I thought it would be too complicated to do, which it wasn't, but it was a bit tricker to get a good working test for this since we listen to mousemove on the document.

Comment (gkatsev) [reply src/js/control-bar/progress-control/seek-bar.js:281]: tests now passing.

File: src/js/slider/slider.js [hunk 3]
```diff
@@ -192,6 +192,7 @@ class Slider extends Component {
    * @param {EventTarget~Event} event
    *        `mousedown`, `mousemove`, `touchstart`, or `touchmove` event that triggered
    *        this function
+   * @param {boolean} mouseDown this is a flag that should be set to true if `handleMouseMove` is called directly. It allows us to skip things that should not happen if coming from mouse down but should happen on regular mouse move handler.
```
Comment (gesinger) [inline src/js/slider/slider.js:195]:
```suggestion
   * @param {boolean} mouseDown this is a flag that should be set to true if `handleMouseMove` is called directly. It allows us to skip things that should not happen if coming from mouse down but should happen on regular mouse move handler. Defaults to false.
```

File: test/unit/controls.test.js [hunk 4]
```diff
@@ -141,6 +143,35 @@ QUnit.test('calculateDistance should use changedTouches, if available', function
...
 
+QUnit.test("SeekBar doesn't set scrubbing on mouse down, only on mouse move", function(assert) {
+  const player = TestHelpers.makePlayer();
+  const scrubbingSpy = sinon.spy(player, 'scrubbing');
+  const seekBar = new SeekBar(player);
+  const doc = new EventTarget();
+
+  // mousemove is listened to on the document.
+  // Specifically, we check the ownerDocument of the seekBar's bar.
+  // Therefore, we want to mock it out to be able to trigger mosuemove
```
Comment (gesinger) [inline test/unit/controls.test.js:154]:
```suggestion
  // Therefore, we want to mock it out to be able to trigger mousemove
```

File: src/js/slider/slider.js (hunk 1 above)
Comment (gkatsev) [reply src/js/slider/slider.js:183]: Created https://github.com/videojs/video.js/issues/7531 to follow up on this.

**Review by gesinger — APPROVED** [review]
