### PR TITLE
fix: Refactor evented to make mincompatable with Chrome 53

### LINKED ISSUE #8783: Uncaught SyntaxError: Unexpected token ( and  Uncaught ReferenceError: videojs is not defined in chrome v 53
### Description

I am working on WebOS LGTV application which using chrome 53 v, I am facing an issue with latest videojs version 8+ but it working fine with videojs version 7+

working fine with below script in chrome version 53
`<script src="https://vjs.zencdn.net/7.21.1/video.min.js"></script>`

getting Uncaught ReferenceError: videojs is not defined error with below given script
image (6)

`<script src="https://vjs.zencdn.net/8.12.0/video.min.js"></script>`

### Reduced test case

NA

### Steps to reproduce

1.chrome v 53
2.
3.

### Errors

Uncaught SyntaxError: Unexpected token ( 
Uncaught ReferenceError: videojs is not defined in chrome v 53

### What version of Video.js are you using?

8.12.0

### Video.js plugins used.

<script src="https://vjs.zencdn.net/8.12.0/video.min.js"></script>

### What browser(s) including version(s) does this occur with?

chrome 53

### What OS(es) and version(s) does this occur with?

webOS and version-1.2.8

### PR DESCRIPTION
**Pull request by mister-ben**
## Description
Chrome 53 doesn't like the minified output. Specifically, it throws `Uncaught SyntaxError: Unexpected token (` on the ternary in the minified version of `normalizeListenArgs()`
https://github.com/videojs/video.js/blob/e78bcc7b2d829fce01451cf105b918d8feec4548/src/js/mixins/evented.js#L165-L195

Line breaks added for clarify

```js
Tt = (e, t, s) => {
  var i = t.length < 3 || t[0] === e || t[0] === e.eventBusEl_;
  let r, n, a;
  return i ? (r = e.eventBusEl_, 3 <= t.length && t.shift(), [n, a] = t) : [r, n, a] = t, ft(r, e, s), yt(n, e, s), bt(a, e, s), a = _(e, a), {
    isTargetingSelf: I,
    target: r,
    type: n,
    listener: a
  }
},
```

Chrome would be happy with this if `[r, n, a] = t` were `([r, n, a] = t)`.

## Specific Changes proposed
Refactor `normalizeListenArgs()` slightly to use multiple statements to coerce uglify-js to include parentheses.
Also updates uglify-js, but that in itself isn't the fix.

Fixes #8783

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [x] Change has been verified in an actual browser - Browserstack Chrome 53
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
  - [x] Has no DOM changes which impact accessiblilty or trigger warnings (e.g. Chrome issues tab)
  - [x] Has no changes to JSDoc which cause `npm run docs:api` to error
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Review by gkatsev — APPROVED** [review]

File: src/js/mixins/evented.js [hunk 1]
```diff
@@ -182,7 +182,10 @@ const normalizeListenArgs = (self, args, fnName) => {
 
     [type, listener] = args;
   } else {
-    [target, type, listener] = args;
+    target = args[0];
```
Comment (gkatsev) [inline src/js/mixins/evented.js:185]: We should add a comment here with a link to this PR so that folks will be less likely to refactor it away.

File: src/js/mixins/evented.js [hunk 2]
```diff
@@ -182,7 +182,12 @@ const normalizeListenArgs = (self, args, fnName) => {
 
     [type, listener] = args;
   } else {
-    [target, type, listener] = args;
+    // This was `[target, type, listener] = args;` but this block needs more than
+    // one statement zto produce minified output compatible with Chrome 53.
```
Comment (gkatsev) [inline src/js/mixins/evented.js:186]: nit,typo:
```suggestion
    // one statement to produce minified output compatible with Chrome 53.
```

**Review by gkatsev — APPROVED** [review]

**Comment by benoit74** [comment]
Any chance to release this soon?

**Comment by mister-ben** [comment]
[8.17.3](https://github.com/videojs/video.js/compare/v8.17.2...v8.17.3) is available and contains the fix. It's not `latest` yet but will be soon.

**Comment by benoit74** [comment]
Thank you!
